### ISSUE TITLE
Add support for request-received middleware

### ISSUE THREAD

**Issue by niftylettuce** [DrBarnabus/koa-req-logger#1]
The `request-received` middleware at https://github.com/cabinjs/request-received exposes a `Symbol.for` property, which this package could conditionally consume if interested (as opposed to just generating a `new Date()`.

e.g. https://github.com/DrBarnabus/koa-req-logger/blob/master/src/index.ts#L198 would change from `ctx.start = new Date();` to `ctx.start = ctx[Symbol.for('request-received.startTime')] ? ctx[Symbol.for('request-received.startTime')] : new Date()`

**Comment by DrBarnabus** [comment]
Thanks for the Suggestion. However, I don't really see how this adds much to the package.

Really all it is doing is replacing a variable with a package that creates the exact same variable behind the scenes.

If there is a significant reason that this is better, then I would be happy to accept the pull request. But at this time I can't really see the benefit.
